# Generated by Django 3.1.3 on 2020-11-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20201125_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='verificacion',
        ),
    ]
